seed: 5
#----change to your own dataset path----#
dataset_path: /home/nsml/hiermambaconv/data/bunny

dataset_type: all 
model:
  model_name: D_NeRV
  act: swish
  stride_list: [5, 4, 4, 2, 2]
  kernel_list: [1, 3, 5, 5, 5]
  padding_list: [0, 1, 2, 2, 2]
  encoder_list: [5, 4, 4, 2, 2]
  diff_enc_list: [4, 2, 2]
  diff_dec_kernel: [3, 3, 3]
  diff_dec_stride: [4]
  diff_dec_padding: [1,1,1]
  conv_type: conv
  c1: 64
  d: 16
  c2: 92 
  height: 640
  width: 1280
train_batchsize: 1
val_batchsize: 1
workers: 4
epoch: 300

optim:
  optim_type: Lion
  lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  lr_schedule: warmup_cosine
  lr_point: 0.1

loss: L2
print_freq: 200
eval_freq: 100

